"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownRight, ArrowUpRight, ChartNoAxesCombined, ChevronDown, Layers3, Settings2, Target } from "lucide-react";

type Range = "7D" | "14D" | "30D";
const daily = [
  {day:"Sep 4",spend:214,value:2190},{day:"Sep 5",spend:268,value:2780},{day:"Sep 6",spend:192,value:1470},{day:"Sep 7",spend:236,value:2150},{day:"Sep 8",spend:310,value:3420},{day:"Sep 9",spend:284,value:3060},{day:"Sep 10",spend:346,value:3770},{day:"Sep 11",spend:392,value:4310},{day:"Sep 12",spend:367,value:4070},{day:"Sep 13",spend:329,value:3360},{day:"Sep 14",spend:415,value:4850},{day:"Sep 15",spend:448,value:5270},{day:"Sep 16",spend:412,value:5060},{day:"Today",spend:386,value:4790},
];
const campaigns = [
  ["The Black Seeds AU Tour","National",1268,15690,12.37,"Scaling","+18%"],
  ["Will Sparks CLASSICS","Melbourne",942,8940,9.49,"On pace","+9%"],
  ["harrykirby — All Your Friends","National",508,3810,7.50,"On pace","+4%"],
  ["Circus Down Under","Sydney",631,2510,3.98,"Watch","−11%"],
] as const;
const pixels=["Less Than Jake — Tour Pixel","Shapeshifter 2026 Pixel","The Black Seeds Pixel","VSPY VSPY Pixel","Will Sparks Pixel","harrykirby pixel"];
const money=(n:number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(n);

export default function Home() {
  const [range,setRange]=useState<Range>("14D");
  const [live,setLive]=useState(false);
  const chart=useMemo(()=>daily.slice(range==="7D"?-7:range==="14D"?-14:0),[range]);
  return <main className="min-h-screen bg-[#f4f3f0] text-[#171717]">
    <div className="mx-auto max-w-[1540px] px-4 py-4 lg:px-7 lg:py-7">
      <header className="flex items-center justify-between border-b border-black/10 pb-5">
        <div className="flex items-center gap-4"><div className="grid h-10 w-10 place-items-center bg-[#ec2227] text-lg font-black text-white">T</div><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-black/50">Teamwrk Touring</p><h1 className="text-lg font-black tracking-[-.04em]">PAID MEDIA HUB</h1></div></div>
        <div className="flex items-center gap-3"><span className={"hidden items-center gap-2 rounded-full px-3 py-1.5 text-xs font-semibold sm:flex "+(live?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-800")}><i className={"h-2 w-2 rounded-full "+(live?"bg-emerald-500":"bg-amber-500")} />{live?"Live Meta data":"Demo data"}</span><button onClick={()=>setLive(!live)} className="inline-flex items-center gap-2 border border-black/15 bg-white px-3 py-2 text-sm font-semibold hover:bg-black hover:text-white"><Settings2 size={15}/>{live?"Connection":"Connect Meta"}</button></div>
      </header>
      <div className="grid gap-7 py-7 lg:grid-cols-[220px_minmax(0,1fr)]">
        <aside className="border-r border-black/10 pr-5 max-lg:hidden"><p className="mb-4 text-[10px] font-bold uppercase tracking-[.18em] text-black/40">Workspace</p><nav className="space-y-1"><a className="flex items-center gap-3 bg-[#171717] px-3 py-2.5 text-sm font-bold text-white" href="#overview"><ChartNoAxesCombined size={17}/>Overview</a><a className="flex items-center gap-3 px-3 py-2.5 text-sm font-semibold text-black/55" href="#campaigns"><Layers3 size={17}/>Campaigns</a><a className="flex items-center gap-3 px-3 py-2.5 text-sm font-semibold text-black/55" href="#pacing"><Target size={17}/>Pacing</a></nav><div className="mt-10 border-t border-black/10 pt-5"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-black/40">Connected account</p><p className="mt-2 text-sm font-bold">Teamwrk Touring</p><p className="font-mono text-[11px] text-black/45">act_1450765939036003</p></div></aside>
        <div className="min-w-0">
          <section id="overview" className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#ec2227]">Daily pacing & return</p><h2 className="mt-1 text-3xl font-black tracking-[-.055em] sm:text-4xl">Know what&apos;s earning its spend.</h2><p className="mt-2 text-sm text-black/55">All active Teamwrk Touring Meta campaigns, measured against their current pace.</p></div><div className="flex w-fit border border-black/15 bg-white p-1">{(["7D","14D","30D"] as Range[]).map(v=><button key={v} onClick={()=>setRange(v)} className={"px-3 py-1.5 text-xs font-bold "+(range===v?"bg-[#171717] text-white":"text-black/45")}>{v}</button>)}</div></section>
          <section className="mt-6 grid gap-px overflow-hidden border border-black/15 bg-black/15 sm:grid-cols-2 xl:grid-cols-4"><Metric l="Spend" v="$5,294" d="72% of weekly pace" t="+12.4%"/><Metric l="Purchase value" v="$64,330" d="Meta-attributed ticket revenue" t="+19.8%"/><Metric l="Blended ROAS" v="12.15x" d="Target: 5.00x" t="+1.14x"/><Metric l="Cost / purchase" v="$6.61" d="801 purchase events" t="−8.2%"/></section>
          <section id="pacing" className="mt-7 grid gap-7 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="border border-black/15 bg-white p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-black/45">Purchase value vs spend</p><h3 className="mt-1 text-xl font-black tracking-[-.035em]">Daily return is holding above target</h3><div className="mt-5 h-[270px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:10,right:0,left:-24,bottom:0}}><defs><linearGradient id="value" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#ec2227" stopOpacity=".28"/><stop offset="100%" stopColor="#ec2227" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#000" strokeOpacity=".08"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:"#737373",fontSize:11}} dy={10}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#737373",fontSize:11}} tickFormatter={v=>"$"+v/1000+"k"}/><Tooltip formatter={(v:number,n:string)=>[money(v),n==="value"?"Purchase value":"Spend"]}/><Area name="spend" type="monotone" dataKey="spend" stroke="#171717" strokeWidth={2} fill="none"/><Area name="value" type="monotone" dataKey="value" stroke="#ec2227" strokeWidth={2.5} fill="url(#value)"/></AreaChart></ResponsiveContainer></div></div><aside className="border border-black/15 bg-[#171717] p-6 text-white"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/45">Today&apos;s pace</p><p className="mt-3 text-4xl font-black tracking-[-.06em]">108%</p><p className="mt-1 text-sm text-white/60">of planned daily return</p><div className="mt-6 h-2 overflow-hidden bg-white/15"><div className="h-full w-[82%] bg-[#ec2227]"/></div><div className="mt-3 flex justify-between text-xs text-white/55"><span>$386 spent</span><span>$4,790 value</span></div><div className="mt-7 border-t border-white/15 pt-5"><p className="text-sm font-bold">Best live result</p><p className="mt-1 text-sm text-white/65">The Black Seeds AU Tour</p><p className="mt-3 text-2xl font-black">12.37x <span className="text-sm font-medium text-white/50">ROAS</span></p></div></aside></section>
          <section id="campaigns" className="mt-7 border border-black/15 bg-white"><div className="flex items-center justify-between border-b border-black/10 px-5 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-black/45">Active campaigns</p><h3 className="mt-1 text-lg font-black tracking-[-.035em]">Where today&apos;s spend is going</h3></div><span className="inline-flex items-center gap-1 text-xs font-bold text-black/55">All campaigns <ChevronDown size={14}/></span></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-black/[.025] text-[10px] uppercase tracking-[.14em] text-black/45"><tr><th className="px-5 py-3">Campaign</th><th className="px-4 py-3">Spend</th><th className="px-4 py-3">Purchase value</th><th className="px-4 py-3">ROAS</th><th className="px-4 py-3">Pacing</th></tr></thead><tbody>{campaigns.map(([tour,city,spend,revenue,roas,status,change])=><tr key={tour} className="border-t border-black/8"><td className="px-5 py-4"><p className="font-bold">{tour}</p><p className="mt-.5 text-xs text-black/45">{city}</p></td><td className="px-4 py-4 text-sm font-semibold">{money(spend)}</td><td className="px-4 py-4 text-sm font-semibold">{money(revenue)}</td><td className="px-4 py-4 font-black text-[#d81f24]">{roas.toFixed(2)}x</td><td className={"px-4 py-4 text-xs font-bold "+(status==="Watch"?"text-amber-700":"text-emerald-700")}><span className="inline-flex items-center gap-1">{status==="Watch"?<ArrowDownRight size={14}/>:<ArrowUpRight size={14}/>} {status} <span className="text-black/40">{change}</span></span></td></tr>)}</tbody></table></div></section>
          <section className="mt-7 grid gap-7 md:grid-cols-2"><div className="border border-black/15 bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-black/45">Data sources detected</p><div className="mt-4 grid gap-2">{pixels.map(p=><div key={p} className="flex justify-between border-b border-black/8 pb-2 text-sm"><span className="font-semibold">{p}</span><span className="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Active</span></div>)}</div></div><div className="border border-black/15 bg-[#ec2227] p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/60">Next connection step</p><h3 className="mt-1 text-xl font-black tracking-[-.04em]">Add your Meta system-user token.</h3><p className="mt-3 text-sm leading-6 text-white/75">The build is ready to pull campaign insights as soon as the secure environment values are added after deployment.</p></div></section>
        </div>
      </div>
    </div>
  </main>;
}

function Metric({l,v,d,t}:{l:string;v:string;d:string;t:string}) { return <div className="bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-black/45">{l}</p><p className="mt-2 text-3xl font-black tracking-[-.055em]">{v}</p><div className="mt-3 flex justify-between gap-2 text-xs"><span className="text-black/48">{d}</span><span className="font-bold text-emerald-700">{t}</span></div></div>; }
