import { writeFile } from "node:fs/promises";
const account=process.env.META_AD_ACCOUNT_ID;
const token=process.env.META_ACCESS_TOKEN;
if(!account||!token) throw new Error("META_AD_ACCOUNT_ID and META_ACCESS_TOKEN are required.");
const fields="campaign_name,spend,actions,action_values";
const url=new URL("https://graph.facebook.com/v24.0/act_"+account+"/insights");
url.searchParams.set("access_token",token);url.searchParams.set("fields",fields);url.searchParams.set("level","campaign");url.searchParams.set("date_preset","last_30d");
const res=await fetch(url);const body=await res.json();if(!res.ok) throw new Error(body.error?.message||"Meta request failed");
const num=x=>Number(x||0);const money=n=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(n);
const rows=body.data||[];const totals=rows.reduce((a,x)=>{a.spend+=num(x.spend);a.value+=num(x.action_values?.find(v=>v.action_type==="offsite_conversion.fb_pixel_purchase")?.value);return a},{spend:0,value:0});
const data={summary:{spend:money(totals.spend),value:money(totals.value),roas:(totals.value/totals.spend||0).toFixed(2)+"x"},daily:[1],campaigns:rows.map(x=>[x.campaign_name,"—",money(num(x.spend)),money(num(x.action_values?.find(v=>v.action_type==="offsite_conversion.fb_pixel_purchase")?.value)),(num(x.action_values?.find(v=>v.action_type==="offsite_conversion.fb_pixel_purchase")?.value)/num(x.spend)||0).toFixed(2)+"x","Live"]),sources:[]};
await writeFile("docs/data/meta-insights.json",JSON.stringify(data));
